---
title: "QUESTION11"
author: "Trevor Schaff"
date: "November 5, 2015"
output: html_document
---

```{r reading in data}
data_exon <- read.csv("data/Homo_sapiens.GRCh38.82.abinitio_exons.gtf", sep="\t")
data_transcript <- read.csv("data/Homo_sapiens.GRCh38.82.abinitio_transcripts.gtf", sep="\t")
names(data_exon)[1]<-"chromosome"
names(data_exon)[4]<-"start"
names(data_exon)[5]<-"end"

names(data_transcript)[1]<-"chromosome"
names(data_transcript)[4]<-"start"
names(data_transcript)[5]<-"end"

```

```{r making new length column}
data_exon$length <- (data_exon$end - data_exon$start)
data_transcript$length <- (data_transcript$end - data_transcript$start)

data_exon_clean <- data_exon[data_exon$chromosome == "1" | data_exon$chromosome == "2"| data_exon$chromosome == "3" | data_exon$chromosome == "4" | data_exon$chromosome == "5" | data_exon$chromosome == "6" | data_exon$chromosome == "7" | data_exon$chromosome == "8" | data_exon$chromosome == "9" | data_exon$chromosome == "10" | data_exon$chromosome == "11" | data_exon$chromosome == "12" | data_exon$chromosome == "13" | data_exon$chromosome == "14" | data_exon$chromosome == "15" | data_exon$chromosome == "16" | data_exon$chromosome == "17" | data_exon$chromosome == "18" | data_exon$chromosome == "19" | data_exon$chromosome == "20" | data_exon$chromosome == "21" | data_exon$chromosome == "X" | data_exon$chromosome == "Y",]

data_transcript_clean <- data_transcript[data_transcript$chromosome == "1" | data_transcript$chromosome == "2"| data_transcript$chromosome == "3" | data_transcript$chromosome == "4" | data_transcript$chromosome == "5" | data_transcript$chromosome == "6" | data_transcript$chromosome == "7" | data_transcript$chromosome == "8" | data_transcript$chromosome == "9" | data_transcript$chromosome == "10" | data_transcript$chromosome == "11" | data_transcript$chromosome == "12" | data_transcript$chromosome == "13" | data_transcript$chromosome == "14" | data_transcript$chromosome == "15" | data_transcript$chromosome == "16" | data_transcript$chromosome == "17" | data_transcript$chromosome == "18" | data_transcript$chromosome == "19" | data_transcript$chromosome == "20" | data_transcript$chromosome == "21" | data_transcript$chromosome == "X" | data_transcript$chromosome == "Y",]


install.packages("plyr")
library(plyr)
exon_data <- ddply(data_exon_clean,~chromosome,summarise,mean=mean(length),sd=sd(length))
transcript_data <- ddply(data_transcript_clean,~chromosome,summarise,mean=mean(length),sd=sd(length))

names(exon_data)[2]<-"exon_length"
names(transcript_data)[2]<-"transcript_length"

recom<-merge(exon_data, transcript_data, by.x="chromosome", by.y="chromosome")


```


